# Generated by Django 3.0.3 on 2020-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkaroslnyprototyp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tradepost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradepost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
