# Generated by Django 3.0.3 on 2020-03-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apkaroslnyprototyp', '0002_auto_20200305_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apkaroslnyprototyp.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidecomment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apkaroslnyprototyp.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradecomment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apkaroslnyprototyp.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradepost',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apkaroslnyprototyp.Profile'),
            preserve_default=False,
        ),
    ]
