# Generated by Django 3.0.3 on 2020-08-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkaroslnyprototyp', '0002_auto_20200818_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
