# Generated by Django 3.0.3 on 2020-03-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkaroslnyprototyp', '0005_auto_20200305_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
