# Generated by Django 3.0.3 on 2020-03-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkaroslnyprototyp', '0006_tradepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepost',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tradepost',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
